import React from 'react';
import Head from 'next/head';

interface Props {
  children?: React.ReactNode;
  pageTitle?: string;
}

export const Header: React.FC<Props> = ({ children, pageTitle }) => {
  return (
    <header>
      <Head>
        <title>{`JobsInGhana - ${
          pageTitle ? pageTitle : "Ghana's leading recruitment site"
        }`}</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='apple-touch-icon'
          sizes='180x180'
          href='/favicon/apple-touch-icon.png'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='32x32'
          href='/favicon/favicon-32x32.png'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='16x16'
          href='/favicon/favicon-16x16.png'
        />
        <link rel='manifest' href='/favicon/site.webmanifest' />
        {children && children}
      </Head>
    </header>
  );
};
